### ISSUE TITLE
Windows 11/ Inkscape 1.2

### ISSUE THREAD

**Issue by babssmm** [Ulzburger/Inkscape-KitePlanGenerator#1]
Hi, I am Bruno, 
I was looking to test the extension for kite design on windows 11/ Inscape 1.2, read the documentation set everything, extension path, doc orientation, extension comes up on the extension drop down menu but nothing happens! any ideia what it can be? 

Many thanks and congratulations for the project, I am with very high expectations 
Best

**Comment by Ulzburger** [comment]
Sorry, it's not runnig with 1.2 only 1.0 and 1 1. When I find some free
time I will analyse what has changed in Inkscape 1.2.

Regard Birger

babssmm ***@***.***> schrieb am Fr., 2. Sept. 2022, 19:10:

**Comment by Ulzburger** [comment]
Issue is solved.

**Comment by babssmm** [comment]
Many thanks, tips was perfect.
excellent
best
Bruno


Em sex., 2 de set. de 2022 às 18:17, Birger Garbe ***@***.***>
escreveu:
